spring:
  application:
    name: ecom.config.server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations:
            - 'file:./ecom-config-store/{application}/{profile}/'
            - 'file:./ecom-config-store/{application}/'
            - 'file:./ecom-config-store/{application}/i18n/'

server:
  port: 8080